Repository livekit/egress, pull requests merged in 2025-09, with the labels that each got.

#986 put egressID back in handler metrics
  pkg/pipeline/controller.go
  pkg/pipeline/sink/segments.go
  pkg/service/metrics.go
  pkg/stats/handler.go
Labels: slack-ts:cs-devs:1756935822.988009

#988 Add content checks to file integration tests - pilot
  test/builder.go
  test/ffprobe.go
  test/file.go
  test/multi.go
  test/test_content.go
Labels: slack-ts:cs-devs:1757068075.739519

#1004 Speed up build time
  .github/workflows/test-integration.yaml
  build/test/Dockerfile
  go.mod
  go.sum
  magefile.go
  pkg/config/manifest.go
  pkg/gstreamer/bin.go
  pkg/gstreamer/callbacks.go
  pkg/gstreamer/state.go
  pkg/info/io.go
  pkg/logging/s3.go
  pkg/pipeline/builder/audio.go
  pkg/pipeline/builder/stream.go
  pkg/pipeline/builder/video.go
  pkg/pipeline/controller.go
  pkg/pipeline/sink/segments.go
  pkg/pipeline/sink/stream.go
  pkg/pipeline/sink/websocket.go
  pkg/pipeline/source/sdk.go
  pkg/pipeline/tempo/controller.go
  pkg/service/metrics.go
  pkg/service/process.go
  pkg/stats/monitor.go
Labels: slack-ts:cs-devs:1758024143.932339

#1011 Enable sync OnRTCP callback in any case
  pkg/pipeline/source/sdk.go
Labels: slack-ts:cs-devs:1758671607.389889

#1013 Skip dummy video packets
  pkg/pipeline/source/sdk/appwriter.go
Labels: slack-ts:cs-devs:1758730988.023359

#1010 Register all GO process metrics
  pkg/handler/handler.go
  pkg/service/metrics.go
Labels: slack-ts:cs-devs:1758668235.525679
