Repository livekit/egress, pull requests merged in 2025-10, with the labels that each got.

#1018 Update Go SDK to pick up track synchronizer logging
  go.mod
  go.sum
Labels: slack-ts:cs-devs:1759315036.092159

#1021 Go SDK for track synchronizer packet stats
  go.mod
  go.sum
Labels: slack-ts:cs-devs:1759385873.917849

#1023 Restore defaultRTPMaxAllowedTsDiff setting
  pkg/config/service.go
Labels: slack-ts:cs-devs:1759402141.569679

#1024 Drop old samples when sample queue overflows.
  go.mod
  go.sum
  pkg/pipeline/source/sdk/appwriter.go
Labels: slack-ts:cs-devs:1759468420.805679

#1007 Adding MP3 to the supported audio types for audio only recordings
  pkg/config/config_test.go
  pkg/config/encoding.go
  pkg/config/output_file.go
  pkg/pipeline/builder/audio.go
  pkg/pipeline/builder/file.go
  pkg/pipeline/builder/muxer.go
  pkg/pipeline/builder/muxer_test.go
  pkg/pipeline/builder/segment.go
  pkg/types/types.go
  test/file.go
Labels: slack-ts:cs-devs:1758908639.765099

#1026 Adding burst estimator
  go.mod
  go.sum
  pkg/config/base.go
  pkg/pipeline/source/sdk.go
  pkg/pipeline/source/sdk/appwriter.go
Labels: slack-ts:cs-devs:1759826060.965889

#1029 Update server-sdk to pull in the fix for initialize timing
  go.mod
  go.sum
  pkg/pipeline/source/sdk/appwriter.go
Labels: slack-ts:cs-devs:1759923218.625389
